# Generated by Django 5.0.4 on 2024-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill_Management_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateId', models.CharField(max_length=80)),
                ('certificateSource', models.CharField(max_length=100)),
                ('certificateNumber', models.CharField(max_length=100)),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDefination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCertificateRequired', models.BooleanField(default=False)),
                ('certificateId', models.CharField(max_length=20)),
                ('SkillDescription', models.CharField(max_length=200)),
                ('skillGroup', models.CharField(max_length=10)),
            ],
        ),
    ]
