# Generated by Django 5.0.4 on 2024-04-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill_Management_Project', '0002_certificate_skilldefination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldefination',
            name='certificateId',
        ),
        migrations.AddField(
            model_name='skilldefination',
            name='certificate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Skill_Management_Project.certificate'),
        ),
        migrations.AddField(
            model_name='skilldefination',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Skill_Management_Project.employee'),
        ),
    ]
