# Generated by Django 5.0.4 on 2024-04-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill_Management_Project', '0004_alter_skilldefination_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldefination',
            name='certificate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Skill_Management_Project.certificate'),
        ),
    ]
